ports:
  - port: 1080
    onOpen: notify
  - port: 1081
    onOpen: notify
  - port: 1082
    onOpen: notify
  - port: 6080
    onOpen: notify
  - port: 6081
    onOpen: notify
  - port: 6082
    onOpen: notify
  - port: 8080
    onOpen: notify
checkoutLocation: "go/src/github.com/xuiv/v2ray-heroku"
workspaceLocation: "go/src/github.com/xuiv/v2ray-heroku"
tasks:
  - init: >
      go get -v ./... &&
      go build -o app
    command: >
      ./app -config server.json
github:
    prebuilds:
        pullRequestsFromForks: true
