image:
  file: .gitpod.dockerfile
ports:
  - port: 1080
    onOpen: notify
  - port: 1081
    onOpen: notify
  - port: 6080
    onOpen: notify
  - port: 8080
    onOpen: notify
checkoutLocation: "go/src/github.com/xuiv/v2ray-heroku"
workspaceLocation: "go/src/github.com/xuiv/v2ray-heroku"
tasks:
  - init: >
      export GO111MODULE=off && go get -v ./... &&
      go build -o app
    command: >
      clear
github:
    prebuilds:
        pullRequestsFromForks: true
